### ISSUE TITLE
trying to evaluate if I can help, and how much

### ISSUE THREAD

**Issue by pierreozoux** [choderalab/coronavirus#17]
Hi,

thanks for your incredible effort :)

I'd like to help, but I'd like to understand a bit more.

Will we find a remedy in one year or in some months (I know you don't know, but I'm sure you have some guess).

If you tell me "every minute count, we can find it in one month", I'll go directly rent GPUs and start folding for you (and spread the word around me, there are many eth miners around the globe that could start working for that instead).

Thanks again for your amazing work!

**Comment by smiroshnikov** [comment]
I am able to provide quite a lot computational power as well , i just need to know more as said on the post above

**Comment by jchodera** [comment]
Thanks for your interest in helping out! I'm afraid we can't easily put any sort of timeline on this, since we can't be sure how long it will take to develop new therapies. Our effort at this point is to assist experimental collaborators (like [DiamondMX](https://www.diamond.ac.uk/covid-19/for-scientists/Main-protease-structure-and-XChem.html)) to rapidly discover new small molecules that may be active in inhibiting viral entry, and to better understand opportunities for targeting the viral protease and other important potential SARS-CoV-2 targets with the goal of accelerating the design or optimization of other therapies. All our data is being made rapidly open to reach the broadest range of scientists working in this area.

A month is an incredibly short time for drug discovery, and while we might hope to identify highly active molecules in that time, there are still a number of downstream steps to understand how those molecules behave in living systems, ensure they are safe, and work out delivery routes that would have to be carried out by entities equipped to do this sort of thing. 

We'd very much appreciate you contributing spare compute cycles, but given the necessary timelines involved, I'd advise against renting GPUs you don't already control since we can't at all guarantee we would have anything like a workable therapy in a month.

**Comment by pierreozoux** [comment]
sounds reasonable thanks.
These are quiet cheap GPUs:
https://www.hetzner.com/dedicated-rootserver/ex51-ssd-gpu/configurator

Even if the therapy would be delivered in 2 months, I still believe that it could save thousands of life.
But maybe I should just give the money to https://www.givewell.org/ - I don't know..

**Comment by jchodera** [comment]
Givewell is a great organization and worthy of support! We're only encouraging the donation of spare compute cycles right now.
