### ISSUE TITLE
What are the OpenMM simulation types that are most relevant?

### ISSUE THREAD

**Issue by rjfnobre** [choderalab/coronavirus#22]
Researcher with some experience with CUDA/OpenCL GPU programming here.

I can try to improve the performance of OpenMM (seems that it is what Folding@Home uses) on the kernels that are the most important for this project.

Please point me to as much relevant information as possible.

**Comment by MariusVanDerWijden** [comment]
Same here, would also like to contribute

**Comment by zasdfgbnm** [comment]
Maybe you can start by running any of these python files, such as https://github.com/FoldingAtHome/coronavirus/blob/master/system-preparation/6acg_6vsb/simulate_6acg_6vsb.py (randomly picked), and do a profiling with nsight systems? https://developer.nvidia.com/nsight-systems

**Comment by proteneer** [comment]
OpenMM is not the easiest code to profile since it generates .cu file and JIT compiles them at run-time.

The most important kernels are:

Real Space calculations:

https://github.com/openmm/openmm/blob/master/platforms/cuda/src/kernels/nonbonded.cu

Reciprocal Space calculations:

https://github.com/openmm/openmm/blob/master/platforms/cuda/src/kernels/pme.cu

**Comment by proteneer** [comment]
@jchodera these are PME calculations right?

**Comment by rafwiewiora** [comment]
They are.

**Comment by jchodera** [comment]
In general, any contributions that accelerate OpenMM are welcomed! Check out the whole codebase here: http://github.com/openmm/openmm
