### ISSUE TITLE
Project Dropdown does not include COVID-19

### ISSUE THREAD

**Issue by nlargebiz** [choderalab/coronavirus#63]
Hi.  In the dropdown for projects when running the client I do not see COVID-19.  I know that there is advantage in selecting the other items or "All Projects" but I would think that at this point in the pandemic that COVID-19 is somewhat higher priority.  Is there going to be an update that allows the users to select the COVID-19 virus from the dropdown [any time soon] ?

Thanks in advance

**Comment by jchodera** [comment]
Thanks for the question! Due to original design limitations, the current client doesn't support pushing new disease categories out. We're working on a new open source client, but it won't be ready for a little while. But rest assured that _all_ GPU projects and all high-priority CPU projects are working on COVID-19! While there's a chance you may get a non-COVID project here and there, that would only be because there is so much interest we're temporarily out of COVID-19 projects.

But we _are_ working on it! We're just focusing on the science right now.

**Comment by jchodera** [comment]
We've now added an option for this! See https://foldingathome.org/2020/04/17/new-foldinghome-software-with-the-option-to-prioritize-covid-19-projects/

**Comment by smares** [comment]
Even though I have COVID-19 set since yesterday, my client just started working on Project 14311 which is an unspecified disease type. Does the "COVID-19" setting also take unspecified disease types into consideration or is there something wrong?

![image](https://user-images.githubusercontent.com/818380/79668879-2b618b80-81b8-11ea-8fd9-0c47606ad5db.png)

**Comment by dimon222** [comment]
@smares it mentions "prioritize", not work only on that category. Possibly F@H simply got out of units working on COVID-19, so assigned whatever else is available in pool.

**Comment by jchodera** [comment]
@dimon222 is right! If there's a temporary lack of COVID-19 WUs, it will still run useful science, and then pick up a COVID-19 WU as soon as it's done.

We're a couple of days away from releasing a new core update that will allow us to get many more COVID-19 WUs out to help us prioritize synthesis of new compounds against the main viral protease for the next stage of the [COVID Moonshot](https://covid.postera.ai/covid). Thanks for bearing with us!
